version: '3.8'

services:
  postgres:
    restart: always
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asd4fgh
      POSTGRES_DB: buymetal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  core-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/buymetal
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: asd4fgh
      SPRING_MINIO_URL : http://minio:9000

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "admin1234"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin1234"
    volumes:
      - ./data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001

volumes:
  postgres-data:
  minio:

