server:
  port: 8080

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name : "buy-metal"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: "jdbc:postgresql://localhost:5432/buymetal"
    username: "postgres"
    password: "asd4fgh"

  jackson:
    serialization:
      fail-on-empty-beans: false

  minio:
    url: http://localhost:9000
    access-key: admin
    secret-key: admin1234
    create-bucket: true
    bucket: "document-storage"

jwt:
  secret: test-secret
  token:
    refresh:
      expire: 30
    access:
      expire: 30

application:
  verification:
    test-code: true
    phone: false
    mail: false

# TODO API
# API for statistics +
# API for generate documents
#
# TODO services
# Service to send mails and sms
# Service to send notifications with sockets
# Add minio
# Add redis ???
# Add rabbit
#
# TODO logic
# Add password recovery +
# Add Email and Phone verification +
# Save order status transition history +
# Templates for mail and docs
#
# Questions
# How to send push notifications
# How to make payments